--- #YAML:1.0
name: Class-DBI-Plugin-Backtickify
version: 0.02
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: surround column and table names with backticks
license: perl
requires:
  Class::DBI: 0
  Class::ISA: 0
  Test::More: 0
provides:
  Class::DBI::Plugin::Backtickify:
    file: lib/Class/DBI/Plugin/Backtickify.pm
    version: 0.02
generated_by: Module::Build version 0.2609
